### ISSUE TITLE
Pint is an invisible dependency

### ISSUE THREAD

**Issue by ehultee** [BryanRiel/iceutils#3]
Ditto last issue: an ImportError is raised if pint is not present, but it's not included in the README/requirements.txt.

> ...File "/home/ehultee/.conda/envs/ehu-gld/lib/python3.7/site-packages/iceutils/tseries/timefn/CenteredBasisFn.py", line 16, in `<module>`
    raise ImportError('Python pint library not available. Please install pint before proceeding.')
ImportError: Python pint library not available. Please install pint before proceeding.

**Comment by ehultee** [comment]
Relatedly: @BryanRiel , I have a requirements.txt in my folder (on mrschippy) but I don't see it on this repo.  It's possible I made the requirements.txt using pip freeze, or it's possible you made it and didn't upload it.  FYI.  Either way, it doesn't include pint.

**Comment by BryanRiel** [comment]
Just added pint in daddc44. I don't have a requirements.txt in the repo, and it's likely I made it on the fly. I'll add some extra details in the README.
