### ISSUE TITLE
Destructor crashes Stack class

### ISSUE THREAD

**Issue by ehultee** [BryanRiel/iceutils#4]
When reading in a Stack from HDF5 of Helheim Glacier velocities, code crashes with error message

> `Exception ignored in: <function Stack.__del__ at 0x7ff251808560>
Traceback (most recent call last):
  File "/home/ehultee/.conda/envs/ehu-gld/lib/python3.7/site-packages/iceutils/stack.py", line 56, in __del__`
>`  File "/home/ehultee/.conda/envs/ehu-gld/lib/python3.7/site-packages/h5py/_hl/files.py", line 412, in close`
>`  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper`
>` File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper`
>`  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids`
>` File "h5py/h5i.pyx", line 40, in h5py.h5i.wrap_identifier`

My impression is that the `__del__` method is being called somehow out of order with python exit/close.  I suspect we don't really need the `__del__` method in this pure Python code ([see here](https://stackoverflow.com/questions/1481488/what-is-the-del-method-how-to-call-it)) so I'd like to try removing it.

**Comment by BryanRiel** [comment]
Just as an experiment, can you try running the following snippet of code to see if it throws an exception (replace `stack.h5` with your Helheim stack):
```
import h5py
fid = h5py.File('stack.h5', 'r')
fid.close()
```
If that works fine, do you mind showing how you're using the `Stack` class in your script? I'd like to get an idea of what could be going wrong. I still support removing `__del__` in this case.

**Comment by ehultee** [comment]
Yeah, that snippet works fine.

My usage is based on what's in the README.  Here it is:

```
import numpy as np
import matplotlib.pyplot as plt
import iceutils as ice
import sys

## Set up combined hdf5 stack
fpath='/home/ehultee/Stack/'
hel_stack = ice.MagStack(files=[fpath+'vx.h5', fpath+'vy.h5'])

```

With `__del__` commented out of the `Stack` class, it works fine.

**Comment by BryanRiel** [comment]
Ok, glad to know it works. I'll try to reproduce the error tomorrow so I can get a better handle on what's throwing an exception. The main reason I implemented `Stack.__del__` was to explicitly close the HDF5 files so that file references wouldn't be left hanging in memory if a `Stack` instance was created in a local context. There's likely a better way to do either do error handling in `__del__` or remove it altogether and add an explicit `close()` method to `Stack`.

**Comment by ehultee** [comment]
I think Python will clean up those references for you--the garbage collector should detect the last use of a reference.  But I get the concern.  

[Python docs](https://docs.python.org/3.5/reference/datamodel.html) suggest a `close()` or a `with` statement, e.g. 
```
def Stack(args):
     def read_new(fid):
          with fid as file:
               [read in necessary HDF5 stuff]
          self.attribute = [stuff read in]
```
This should close the HDF5 as soon as you've taken the necessary info and assigned it.

I don't think I'd do error handling in `__del__`, since it might not always run and could produce hard-to-trace errors.  In any case, commenting out `__del__` works for my purposes.  Do you have an example of what usage would create the problem you're trying to mitigate?

**Comment by BryanRiel** [comment]
Ok, it looks like the scenario I was thinking about was an issue way back in 2012, and the lead developer of h5py addressed it in 2014 by adding an ability to auto-close file objects when all attached Files and Groups have been closed:

https://github.com/h5py/h5py/issues/246

So yeah, goodbye to `__del__`!

**Comment by ehultee** [comment]
Nice!  I've removed it in the tagged commits and PR.
